networks:
  default:
    name: amnezia-docker-network
    
services:
  ssh-service:
    build: .
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket
      - ./authorized_keys:/root/.ssh/authorized_keys
      - ./ssh-keys:/etc/ssh/server-keys
